### ISSUE TITLE
Plugin should not allow on dots '.' in field names

### ISSUE THREAD

**Issue by koman-maciej** [fabric8io/fluent-plugin-docker_metadata_filter#9]
ElasticSearch in version 2.0 (or higher) expects field names without dots `.` - according to the https://discuss.elastic.co/t/field-name-cannot-contain/33251.

It makes a problem, especially when docker label contains dot (e.g. container running by docker-compose obtains `com.docker.compose.config-hash` label by default). There is no protection against that situation, so it causes `MapperParsingException`:

```
[2016-07-19 13:12:52,569][DEBUG][action.bulk              ] [M-Twins] [logstash-2016.07.19][0] failed to execute bulk item (index) index {[logstash-2016.07.19][fluentd][AVYDSZ_SsOTWGNsC-CJe], source[{"log":"\n","stream":"stdout","docker":{"id":"8ffe1c63a5cdaa48957645daf6730a2666fdac30d8eeff6b98c317d6811a146b","name":"dev_redis_1","container_hostname":"localhost","image":"redis","image_id":"sha256:bced161d33aeeb4b543b18c1f0fbf381b088e2d849f2ad7bbd209b0a3d2f71bc","labels":{"com.docker.compose.config-hash":"2a8e9c24dd3c46ac16427834db81bfcc95e8b9fc9c7eeaa62de47d61ca04b133","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"dev","com.docker.compose.service":"redis","com.docker.compose.version":"1.5.1"}},"tag":"docker.var.lib.docker.containers.8ffe1c63a5cdaa48957645daf6730a2666fdac30d8eeff6b98c317d6811a146b.8ffe1c63a5cdaa48957645daf6730a2666fdac30d8eeff6b98c317d6811a146b-json.log","@timestamp":"2016-07-19T10:03:00+00:00"}]}
MapperParsingException[Field name [com.docker.compose.config-hash] cannot contain '.']
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:273)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:193)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:305)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:193)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:305)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

My suggestion is to add property for replacing dots in unchecked fields like labels section

**Comment by jimmidyson** [comment]
Thanks for the report. We've done this precise thing for our Kubernetes fluentd plugin. Unfortunately this plugin is no longer maintained. I'd recommend you fork it & make the required changes. Sorry!
